InfluencersApp/Controllers/ArticleController.cs
using BusinessLogic.Interfaces;
using BusinessLogic.Models;
using InfluencersApp.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace InfluencersApp.Controllers
{
    public class ArticleController : Controller
    {        
        private readonly ILogger<ArticleController> _logger;

        private string _articleSubmitMessage = "";

        private readonly IArticleService _articleService;

        private readonly IConfiguration _configuration;

        public ArticleController(ILogger<ArticleController> logger, IArticleService articleService, IConfiguration configuration)
        {            
            _logger = logger;

            _articleService = articleService;

            _configuration = configuration;
        }     
            
        public IActionResult CreateArticle()
        {
            ViewData["Message"] = _articleSubmitMessage;

            return View();
        }       

        [HttpPost]        
        public async Task<IActionResult> CreateArticle(CreateArticleViewModel viewModel)
        {           
            if (viewModel.CreateArticleData.Title == null || 
                viewModel.CreateArticleData.Content == null || 
                viewModel.CreateArticleData.AuthorEmail == null ||
                viewModel.CreateArticleData.AuthorNickname == null ||
                viewModel.CreateArticleData.Tags == null)
            {
                _articleSubmitMessage = "Can't submit article, invalid input...";

                ViewData["Message"] = _articleSubmitMessage;

                return View();
            }

            await _articleService.AddArticle(viewModel.CreateArticleData);

            var emailViewModel = new EmailViewModel
            {
                To = viewModel.CreateArticleData.AuthorEmail,
                IsHtml = false,
                Subject = "Article added...",
                Content = $"Hi { viewModel.CreateArticleData.AuthorNickname }, " +
                $"we've sent you this confirmation email so that we can verify it's you"
            };

            await emailViewModel.SendEmail(_configuration);

            _articleSubmitMessage = "Article was submitted successfuly";

            ViewData["Message"] = _articleSubmitMessage;

            return View(); 
        }

        [HttpGet("article/articleDetails/{id}")]       
        public async Task<IActionResult> ArticleDetails(int id)
        {
            var viewModel = await _articleService.GetArticleDetailsViewModel(id);

            return View(viewModel);
        }
        
        [HttpGet("article/editArticle/{id}")]
        public async Task<IActionResult> EditArticle(int id)
        {
            var articleDetailsViewModel = await _articleService.GetArticleDetailsViewModel(id);

            var editArticleViewModel = new EditArticleViewModel
            {
                ArticleDetailsViewModel = articleDetailsViewModel
            };

            return View(editArticleViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SubmitChanges(EditArticleViewModel viewModel)
        {           
            await _articleService.UpdateArticle(viewModel.ArticleDetailsViewModel.ArticleDetails);

            viewModel.EmailViewModel = new EmailViewModel
            {
                To = viewModel.ArticleDetailsViewModel.ArticleDetails.AuthorEmail,
                IsHtml = false,
                Subject = $"Article content changed...",
                Content = $"Hi { viewModel.ArticleDetailsViewModel.ArticleDetails.AuthorNickname }, " +
                $"we've sent you this confirmation email so that we can verify it's you"
            };

            await viewModel.EmailViewModel.SendEmail(_configuration);

            return Redirect($"articleDetails/{viewModel.ArticleDetailsViewModel.ArticleDetails.ArticleId}");
        }
    }
}

InfluencersApp/Controllers/AuthorController.cs
using BusinessLogic.Interfaces;
using BusinessLogic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace InfluencersApp.Controllers
{
    public class AuthorController : Controller
    {        
        private readonly ILogger<AuthorController> _logger;

        private readonly IAuthorService _authorService;

        public AuthorController(ILogger<AuthorController> logger, IAuthorService authorService)
        {            
            _logger = logger;

            _authorService = authorService;
        }

        [HttpGet]
        public async Task<IActionResult> Rankings(int choice)
        {
            var viewModel = new RankingViewModel();
            
            if (choice == 0)
            {
                ViewData["By"] = "(Score)";

                viewModel = await _authorService.GetAuthorsByScore();
                viewModel.Choice = choice;
            }
            else if (choice == 1)
            {
                ViewData["By"] = "(Number Of Articles)";

                viewModel = await _authorService.GetAuthorsByNumberOfArticles();
                viewModel.Choice = choice;
            }
            else if (choice == 2)
            {
                ViewData["By"] = "(Number Of Commented Articles)";

                viewModel = await _authorService.GetAuthorsByCommentedArticles();
                viewModel.Choice = choice;
            }

            return View(viewModel);
        }                 
    }
}

InfluencersApp/Views/Shared/_Layout.cshtml
@{ 
    var byScore = new Dictionary<string, string> { { "choice", "0" } };
    var byNumberOfArticles = new Dictionary<string, string> { { "choice", "1" } };
    var byCommentedArticles = new Dictionary<string, string> { { "choice", "2" } };
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InfluencersApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/commentSection.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InfluencersApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="CreateArticle">Create Article</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" id="navbarDropdown"
                               asp-area="" asp-controller="Author" asp-action="Rankings"
                               data-toggle="dropdown">
                                View Rankings
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Author" asp-action="Rankings"
                                   asp-all-route-data="byScore">
                                    By Score
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Author" asp-action="Rankings"
                                   asp-all-route-data="byNumberOfArticles">
                                    By Number Of Articles
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Author" asp-action="Rankings"
                                   asp-all-route-data="byCommentedArticles">
                                    By Commented Articles
                                </a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InfluencersApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/starRating.js" asp-append-version="true"></script>
    <script src="~/js/vote.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-cookie/jquery.cookie.js"></script>
    <script src="~/js/comment.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>